### ISSUE TITLE
请求帮助

### ISSUE THREAD

**Issue by hzy2003** [fython/PackageTracker-NodeServer#12]
`module.js:549
    throw err;
    ^

Error: Cannot find module './models/User'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/PackageTracker/subscribeapi.js:2:14)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/PackageTracker/server.js:6:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
`
请问这一段报错有什么问题吗？
已进行npm install

**Comment by WordlessEcho** [comment]
Rerun `npm install` and pay attention to the logs.
